version: '3.3'
services:
    bitessentials:
        container_name: bitessentials
        restart: unless-stopped
        volumes:
            - $PWD/config.json:/BitEssentials/config.json
        image: 'emonq/bitessentials:latest'